### ISSUE TITLE
feat: Replacing assets on Main site

### ISSUE THREAD

**Issue by yehjxraymond** [BluejayFinance/bluejay-website#1]
To replace the current marketing website with the new design:
![image](https://user-images.githubusercontent.com/7406870/152274932-0b31dcd9-219c-4cdf-b6e2-2f2afe487565.png)

Assets:
https://drive.google.com/drive/u/2/folders/1IFfFAJ16WKSlmTpEXDK7hnn7VKj_x5uD

---

WIP:
This is the design that is a work in progress, keeping it here first: https://www.figma.com/file/CW7WA86cVAd9FMdDL5nwWk/Bluejay-Landing?node-id=0%3A1

**Comment by shonoru** [comment]
Need access to assets, sent request

**Comment by yehjxraymond** [comment]
Have granted access to your org email for the folder
